#!/bin/sh

# type: string
# description: usleep path if available
has_usleep=""

_cols=$(tput cols)
halfcol=$(( _cols / 2 ))

# Usage: getval "KEY" file
# Return: string
# Description:
#   Read a KEY=VALUE file and retrieve the Value of the passed KEY
getval(){
  # Setting 'IFS' tells 'read' where to split the string.
  while IFS='=' read -r key val; do
    # Skip over lines containing comments.
    # (Lines starting with '#').
    [ "${key##\#*}" ] || continue

    # '$key' stores the key.
    # '$val' stores the value.
    if [ "$key" = "$1" ]; then
      printf '%s\n' "$val"
    fi
  done < "$2"
}

bat_icon=""
FANCY_BAT_ICON=""

if [ -r "$CONF" ]; then
    FANCY_BAT_ICON=$(getval "FANCY_BAT_ICON" "$CONF")
fi

if [ -n "$FANCY_BAT_ICON" ]; then
    bat1i=
    bat2i=
    bat3i=
    bat4i=
    bat5i=
else
    bat1i=▁
    bat2i=▂
    bat3i=▄
    bat4i=▆
    bat5i=█
fi

batpath=""
batlocation=/sys/class/power_supply
usebat=""
for batpath in "${batlocation}"/BAT*; do
    if [ -r "$batpath"/capacity  ]; then
        usebat="$batpath"
        # yes we really only care about the first battery we can find
        break
    fi
done

getbat() {
    if [ -n "${usebat}" ]; then
        bat_level=$(cat "${usebat}"/capacity)
        case "$bat_level" in
            [0-9]|1[0-9])
                bat_icon="$bat1i"
                ;;
            2[0-9]|3[0-9])
                bat_icon="$bat2i"
                ;;
            4[0-9]|5[0-9])
                bat_icon="$bat3i"
                ;;
            6[0-9]|7[0-9])
                bat_icon="$bat4i"
                ;;
            8[0-9]|9[0-9]|100)
                bat_icon="$bat5i"
                ;;
        esac
        printf '%s %3s' "$bat_icon" "${bat_level}%"
    else
        printf '      '
    fi
}

wbat=6
wday=10
wtime=8
spaces=6
padding=$(( halfcol - (( wday + wtime + wbat + spaces ) / 2 ) ))

[ -z "$AuthFgColor" ] && AuthFgColor="#c1c1c3"
AuthFgColor="${AuthFgColor#*#}"
fgr=$(printf '0x%0.2s\n' "${AuthFgColor}")
fgr=$(printf '%d\n' "$fgr")
fgg=$(printf '0x%0.2s\n' "${AuthFgColor#??}")
fgg=$(printf '%d\n' "$fgg")
fgb=$(printf '0x%0.2s\n' "${AuthFgColor#????}")
fgb=$(printf '%d\n' "$fgb")
[ -z "$AuthBgColor" ] && AuthBgColor="#5f7397"
AuthBgColor="${AuthBgColor#*#}"
bgr=$(printf '0x%0.2s\n' "${AuthBgColor}")
bgr=$(printf '%d\n' "$bgr")
bgg=$(printf '0x%0.2s\n' "${AuthBgColor#??}")
bgg=$(printf '%d\n' "$bgg")
bgb=$(printf '0x%0.2s\n' "${AuthBgColor#????}")
bgb=$(printf '%d\n' "$bgb")

# fgcol="${fgr};${fgg};${fgb}"
# bgcol="${bgr};${bgg};${bgb}"

# esc='\033'

# echo $_cols

exit_handler() {
    printf '\33[?25h'
}

ontop () {
    xdotool windowraise "$WINDOWID"
}

# usage: msleep int
# description: sleep for milliseconds
# return type: void
msleep () {
    milisecs="$1"
    if [ -n "$has_usleep" ]; then
        microsecs="${milisecs}000"
        case "$has_usleep" in
            */usleep)
                usleep "$microsecs"
                ;;
            */busybox)
                busybox usleep "$microsecs"
                ;;
        esac
    else
        secs=$(awk -v s="${milisecs}" 'BEGIN {printf "%.3f", s/1000}')
        sleep "$secs"
    fi
}

has_usleep=$(command -v usleep)
[ -z "$has_usleep" ] && has_usleep=$(command -v busybox)

printf '\33[?25l'
cont=1
while [ "$cont" = 1 ]; do
    ontop
    cday=$(date '+%Y %m %d')
    ctime=$(date '+%T')
    cbat="$(getbat)"
    printf ' %*s ' "$wday" "$cday"
    printf '%*s' "$padding" " "
    printf '\033[38;2;%s;%s;%sm' "${fgr}" "${fgg}" "${fgb}"
    printf '\033[48;2;%s;%s;%sm' "${bgr}" "${bgg}" "${bgb}"
    printf ' %*s ' "$wtime" "$ctime"
    printf '\033[0m'
    printf '%*s' "$padding" " "
    printf ' %*s ' "$wbat" "$cbat"
    printf '\r'
    msleep 500
done

trap 'exit_handler' EXIT
